### ISSUE TITLE
GPG Signing

### ISSUE THREAD

**Issue by scj643** [NCommander/vaksina#5]
Given the sensitive nature of this project I purpose that GPG signing is enforced. 

https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

**Comment by amcgregor** [comment]
On-site validation of signatures (e.x. ["verified" badges here](https://github.com/marrow/uri/commits/develop)) helps avoid one of the minor issues of GitHub. 🤨 Minor enough to permit embedding YouTube-dl's repository within GitHub's own DMCA takedown notice repository; that is, it is possible to inject objects (deltas) into other repositories.

Not just a good idea for branch limitations, but also on anything deployable, verify during the build phase. 👍
